# Generated by Django 3.2.8 on 2021-10-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(default='', max_length=75)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
